### ISSUE TITLE
ValueError: Cannot feed value of shape (128, 15, 15, 1) for Tensor u'Placeholder_1:0', which has shape '(?, 21, 21, 1)'

### ISSUE THREAD

**Issue by rose0826** [liliumao/Tensorflow-srcnn#2]
I installed tensorflow and run model/image/mnist/convolutional.py successfully.
And I download Tensor-srcnn and run generate_train.m and generate_test.m successfully (bring store2hdf5.m from original SRCNN).
After that, when I run python srcnn.py, this error occurred.

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.48GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From srcnn.py:96 in run_benchmark.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "srcnn.py", line 124, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "srcnn.py", line 120, in main
    run_benchmark()
  File "srcnn.py", line 110, in run_benchmark
    _,step = sess.run([train_op, global_step], feed_dict={images:batch_data, labels:batch_label})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 718, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (128, 15, 15, 1) for Tensor u'Placeholder_1:0', which has shape '(?, 21, 21, 1)'

How can I solve this problem?
Thank you in advance.

**Comment by Goolley** [comment]
Simply modified file generate_train.m label = 15 to label = 21.

**Comment by rose0826** [comment]
I didn't think generate_train.m were changed from the original one.
I understand well.
Thank you.
